// Reading and (re)writing .env for the setup wizard.
//
// Write behaviour is a clean regenerate: we emit a fresh .env from the manifest
// (section headers in a fixed order) rather than patching the original file in
// place. That keeps the file tidy and self-documenting; the cost is that a
// user's hand-added comments/ordering are not preserved — but unknown KEY=value
// lines ARE carried over into a trailing block so no actual config is lost.
//
// The parser also powers sync mode: a variable counts as "known" whether it is
// set (`KEY=value`) or written as a declined placeholder (`# KEY=`), which is
// exactly how sync distinguishes "asked and declined" from "new, never asked".

import { readFileSync, writeFileSync } from "node:fs";
import { SECTIONS, allKeys } from "./manifest.js";

const KEY_RE = /^([A-Z][A-Z0-9_]*)=(.*)$/;
const COMMENTED_KEY_RE = /^#\s*([A-Z][A-Z0-9_]*)\s*=/;

export interface ParsedEnv {
  /** Live key→value pairs (uncommented assignments). */
  values: Record<string, string>;
  /** Every key that appears, set OR as a `# KEY=` placeholder. */
  known: Set<string>;
  /** `KEY=value` lines for keys the manifest doesn't know about — preserved on rewrite. */
  extra: Array<{ key: string; value: string }>;
  /** Whether the file existed at all. */
  exists: boolean;
}

export function parseEnv(path: string): ParsedEnv {
  let raw: string;
  try {
    raw = readFileSync(path, "utf8");
  } catch {
    return { values: {}, known: new Set(), extra: [], exists: false };
  }

  const values: Record<string, string> = {};
  const known = new Set<string>();
  const manifestKeys = new Set(allKeys());
  const extra: Array<{ key: string; value: string }> = [];

  for (const line of raw.split("\n")) {
    const commented = line.match(COMMENTED_KEY_RE);
    if (commented) {
      known.add(commented[1]);
      continue;
    }
    const m = line.match(KEY_RE);
    if (!m) continue;
    const [, key, rawValue] = m;
    const value = unquote(rawValue.trim());
    values[key] = value;
    known.add(key);
    if (!manifestKeys.has(key)) extra.push({ key, value });
  }

  return { values, known, extra, exists: true };
}

function unquote(v: string): string {
  if (v.length >= 2 && ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'")))) {
    return v.slice(1, -1);
  }
  return v;
}

// Quote a value only when it needs it (spaces, #, or leading/trailing space),
// so simple values stay bare and readable.
function quoteIfNeeded(v: string): string {
  if (v === "") return "";
  if (/[\s#'"]/.test(v) || v !== v.trim()) return JSON.stringify(v);
  return v;
}

// Three states a manifest var can be in when writing .env:
//   set      → `KEY=value`         (has a real value)
//   declined → `# KEY=`            (explicitly skipped; marks the key "known" so
//                                    sync mode won't re-ask it)
//   (absent) → omitted entirely    (never asked, e.g. a Quick-setup var; a later
//                                    sync run WILL offer it because it's unknown)
export type EntryState = "set" | "declined";
export interface Entry {
  state: EntryState;
  value: string;
}

/** Keys absent from the map are "never asked" and omitted from the output. */
export type Collected = Record<string, Entry>;

const RULE = "═".repeat(78);

/**
 * Serialize a fresh .env from the manifest and the collected values. Vars are
 * emitted in section order; a section with no collected vars is skipped whole so
 * a Quick setup doesn't leave a wall of empty headers. Unknown keys from the
 * previous file are kept in a trailing block.
 */
export function serializeEnv(collected: Collected, extra: Array<{ key: string; value: string }>): string {
  const out: string[] = [
    "# okffs configuration — generated by `okffs setup`.",
    "# .env is git-ignored and loaded automatically from the directory okffs runs in.",
    "# Re-run `okffs setup` any time (e.g. after upgrading) to pick up new options.",
    "",
  ];

  for (const section of SECTIONS) {
    const keys = [...(section.gateKey ? [section.gateKey] : []), ...section.vars.map((v) => v.key)];
    if (!keys.some((k) => collected[k])) continue; // whole section unasked — skip it

    out.push(`# ${RULE}`);
    out.push(`# ${section.title}`);
    out.push(`# ${RULE}`);
    if (section.blurb) out.push(`# ${section.blurb}`);
    out.push("");

    for (const k of keys) emitVar(out, k, collected);
    out.push("");
  }

  if (extra.length > 0) {
    out.push(`# ${RULE}`);
    out.push("# Other (preserved from your previous .env)");
    out.push(`# ${RULE}`);
    for (const { key, value } of extra) out.push(`${key}=${quoteIfNeeded(value)}`);
    out.push("");
  }

  return out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}

function emitVar(out: string[], key: string, collected: Collected): void {
  const e = collected[key];
  if (!e) return; // never asked — omit so a later sync run offers it
  if (e.state === "declined" || e.value === "") {
    out.push(`# ${key}=`);
  } else {
    out.push(`${key}=${quoteIfNeeded(e.value)}`);
  }
}

export function writeEnv(path: string, contents: string): void {
  writeFileSync(path, contents, "utf8");
}
